const { contextBridge, ipcRenderer, clipboard } = require('electron');

contextBridge.exposeInMainWorld('api', {
  pickFile: () => ipcRenderer.invoke('pick-file'),
  load: (target) => ipcRenderer.invoke('player:load', target),
  play: () => ipcRenderer.invoke('player:play'),
  pause: () => ipcRenderer.invoke('player:pause'),
  togglePlayPause: () => ipcRenderer.invoke('player:toggle-play'),
  seek: (secs) => ipcRenderer.invoke('player:seek', secs),
  setVolume: (vol) => ipcRenderer.invoke('player:volume', vol),
  stop: () => ipcRenderer.invoke('player:stop'),
  discoverDlna: () => ipcRenderer.invoke('dlna:discover'),
  browseDlna: (server, objectId) => ipcRenderer.invoke('dlna:browse', server, objectId),
  startRenderer: () => ipcRenderer.invoke('renderer:start'),
  stopRenderer: () => ipcRenderer.invoke('renderer:stop'),
  rendererStatus: () => ipcRenderer.invoke('renderer:status'),
  getSettings: () => ipcRenderer.invoke('settings:get'),
  setAutoStart: (value) => ipcRenderer.invoke('settings:set-auto-start', value),
  setInterface: (name) => ipcRenderer.invoke('settings:set-interface', name),
  setVideoRect: (rect) => ipcRenderer.send('player:set-video-rect', rect),
  onNowPlaying: (cb) => ipcRenderer.on('player:now-playing', (_evt, info) => cb(info)),
  onCastActivity: (cb) => ipcRenderer.on('cast:activity', (_evt, info) => cb(info)),
  onCastSource: (cb) => ipcRenderer.on('cast:source', (_evt, info) => cb(info)),
  seekAbsolute: (secs) => ipcRenderer.invoke('player:seek-absolute', secs),
  toggleMute: () => ipcRenderer.invoke('player:toggle-mute'),
  toggleSubtitles: () => ipcRenderer.invoke('player:toggle-subtitles'),
  cycleSubtitleTrack: () => ipcRenderer.invoke('player:cycle-subtitle-track'),
  cycleAudioTrack: () => ipcRenderer.invoke('player:cycle-audio-track'),
  screenshot: () => ipcRenderer.invoke('player:screenshot'),
  playerSetVideoTrack: (trackId) => ipcRenderer.invoke('player:set-video-track', trackId),
  playerReturnToLiveEdge: () => ipcRenderer.invoke('player:return-to-live-edge'),
  getFitModes: () => ipcRenderer.invoke('player:get-fit-modes'),
  setFitMode: (id) => ipcRenderer.invoke('player:set-fit-mode', id),
  toggleFullscreen: () => ipcRenderer.invoke('player:toggle-fullscreen'),
  toggleLiveMode: () => ipcRenderer.invoke('player:toggle-live-mode'),
  onPlayerStatus: (cb) => ipcRenderer.on('player:status', (_evt, info) => cb(info)),
  onPlayerTracks: (cb) => ipcRenderer.on('player:tracks', (_evt, info) => cb(info)),
  onActivity: (cb) => ipcRenderer.on('player:activity', () => cb()),
  onFullscreenChanged: (cb) => ipcRenderer.on('player:fullscreen-changed', (_evt, v) => cb(v)),
  setAudioTrack: (id) => ipcRenderer.invoke('player:set-audio-track', id),
  setSubtitleTrack: (id) => ipcRenderer.invoke('player:set-subtitle-track', id),
  setSpeed: (value) => ipcRenderer.invoke('player:set-speed', value),
  getMediaInfo: () => ipcRenderer.invoke('player:get-media-info'),
  toggleAlwaysOnTop: () => ipcRenderer.invoke('window:toggle-always-on-top'),
  getAlwaysOnTop: () => ipcRenderer.invoke('window:get-always-on-top'),
  copyText: (text) => clipboard.writeText(text),
});
